### <a name="workflow-now-throws-original-exception-instead-of-nullreferenceexception-in-some-cases"></a><span data-ttu-id="07845-101">Flux de travail présent lève une exception d’origine au lieu de l’exception NullReferenceException dans certains cas</span><span class="sxs-lookup"><span data-stu-id="07845-101">Workflow now throws original exception instead of NullReferenceException in some cases</span></span>

|   |   |
|---|---|
|<span data-ttu-id="07845-102">Détails</span><span class="sxs-lookup"><span data-stu-id="07845-102">Details</span></span>|<span data-ttu-id="07845-103">Dans le .NET Framework 4.6.2 et les versions antérieures, lorsque la méthode d’exécution d’une activité de workflow lève une exception avec un <code>null</code> la valeur pour le <xref:System.Exception.Message> propriété, le runtime de flux de travail System.Activities lève un <xref:System.NullReferenceException?displayProperty=name>, masquage le exception d’origine. Dans le 4.7 .NET Framework, l’exception précédemment masquée est levée.</span><span class="sxs-lookup"><span data-stu-id="07845-103">In the .NET Framework 4.6.2 and earlier versions, when the Execute method of a workflow activity throws an exception with a <code>null</code> value for the <xref:System.Exception.Message> property, the System.Activities Workflow runtime throws a <xref:System.NullReferenceException?displayProperty=name>, masking the original exception.In the .NET Framework 4.7, the previously masked exception is thrown.</span></span>|
|<span data-ttu-id="07845-104">Suggestion</span><span class="sxs-lookup"><span data-stu-id="07845-104">Suggestion</span></span>|<span data-ttu-id="07845-105">Si votre code repose sur la gestion de la <xref:System.NullReferenceException?displayProperty=name>, modifiez-le afin d’intercepter les exceptions qui peuvent être levées à partir de vos activités personnalisées.</span><span class="sxs-lookup"><span data-stu-id="07845-105">If your code relies on handling the <xref:System.NullReferenceException?displayProperty=name>, change it to catch the exceptions that could be thrown from your custom activities.</span></span>|
|<span data-ttu-id="07845-106">Portée</span><span class="sxs-lookup"><span data-stu-id="07845-106">Scope</span></span>|<span data-ttu-id="07845-107">Mineur</span><span class="sxs-lookup"><span data-stu-id="07845-107">Minor</span></span>|
|<span data-ttu-id="07845-108">Version</span><span class="sxs-lookup"><span data-stu-id="07845-108">Version</span></span>|<span data-ttu-id="07845-109">4.7</span><span class="sxs-lookup"><span data-stu-id="07845-109">4.7</span></span>|
|<span data-ttu-id="07845-110">Type</span><span class="sxs-lookup"><span data-stu-id="07845-110">Type</span></span>|<span data-ttu-id="07845-111">Runtime</span><span class="sxs-lookup"><span data-stu-id="07845-111">Runtime</span></span>|
|<span data-ttu-id="07845-112">API affectées</span><span class="sxs-lookup"><span data-stu-id="07845-112">Affected APIs</span></span>|<ul><li><xref:System.Activities.CodeActivity.Execute(System.Activities.CodeActivityContext)?displayProperty=nameWithType></li><li><xref:System.Activities.AsyncCodeActivity.BeginExecute(System.Activities.AsyncCodeActivityContext,System.AsyncCallback,System.Object)?displayProperty=nameWithType></li><li><xref:System.Activities.AsyncCodeActivity%601.BeginExecute(System.Activities.AsyncCodeActivityContext,System.AsyncCallback,System.Object)?displayProperty=nameWithType></li><li><xref:System.Activities.WorkflowInvoker.Invoke?displayProperty=nameWithType></li></ul>|

